In [17]:
import numpy as np
from numpy.linalg import *
import csv
import math

In [18]:
# 格式化数据
file_reader = csv.reader(open("watermelon3.csv","r",encoding='utf-8'))
file_writer= csv.writer(open("data_exe.csv","w",encoding='utf-8',newline=''))
data_pre=[]
for i in file_reader:
    data_pre.append(i)
name=data_pre[0]
# 用一个变量记录表头后，去除data_pre中的表头
del (data_pre[0])
data_exe = data_pre
print(data_exe)
seze = {"青绿":1, "乌黑":0.5, "浅白":0}
gendi = {"蜷缩":1, "稍蜷":0.5, "硬挺":0}
qiaosheng = {"浊响":1, "沉闷":0.5, "清脆":0}
wenli = {"清晰":1, "稍糊":0.5, "模糊":0}
qibu = {"凹陷":1, "稍凹":0.5, "平坦":0}
chugan = {"硬滑":1, "软粘":0}
haogua = {"是":1, "否":0}
# 0编号	1色泽	2根蒂	3敲声	4纹理	5脐部	6触感	7密度	8含糖率	 9好瓜
for i in data_exe:
    i[1]=seze[i[1]]
    i[2]=gendi[i[2]]
    i[3]=qiaosheng[i[3]]
    i[4]=wenli[i[4]]
    i[5]=qibu[i[5]]
    i[6]=chugan[i[6]]
    i[9]=haogua[i[9]]

# 将处理完的列表数据写入文件
file_writer.writerow(name) # 写入表头
file_writer.writerows(data_exe)
data=np.asarray(data_exe)
print(data)

[['1', '青绿', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '0.697', '0.46', '是'], ['2', '乌黑', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '0.774', '0.376', '是'], ['3', '乌黑', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '0.634', '0.264', '是'], ['4', '青绿', '蜷缩', '沉闷', '清晰', '凹陷', '硬滑', '0.608', '0.318', '是'], ['5', '浅白', '蜷缩', '浊响', '清晰', '凹陷', '硬滑', '0.556', '0.215', '是'], ['6', '青绿', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '0.403', '0.237', '是'], ['7', '乌黑', '稍蜷', '浊响', '稍糊', '稍凹', '软粘', '0.481', '0.149', '是'], ['8', '乌黑', '稍蜷', '浊响', '清晰', '稍凹', '硬滑', '0.437', '0.211', '是'], ['9', '乌黑', '稍蜷', '沉闷', '稍糊', '稍凹', '硬滑', '0.666', '0.091', '否'], ['10', '青绿', '硬挺', '清脆', '清晰', '平坦', '软粘', '0.243', '0.267', '否'], ['11', '浅白', '硬挺', '清脆', '模糊', '平坦', '硬滑', '0.245', '0.057', '否'], ['12', '浅白', '蜷缩', '浊响', '模糊', '平坦', '软粘', '0.343', '0.099', '否'], ['13', '青绿', '稍蜷', '浊响', '稍糊', '凹陷', '硬滑', '0.639', '0.161', '否'], ['14', '浅白', '稍蜷', '沉闷', '稍糊', '凹陷', '硬滑', '0.657', '0.198', '否'], ['15', '乌黑', '稍蜷', '浊响', '清晰', '稍凹', '软粘', '0.36', '0.37', '否'], ['16',

In [19]:
# 初始化omega，b，beta，x
# np.astype(np.float) 转换数据类型
x_hat=np.concatenate((data[:,1:7].astype(np.float),np.zeros((17,1),dtype=int)+1),axis=1)         # 沿轴1连接array数组, 形成hat(x) 矩阵
y=data[:,9].astype(np.float)                                    # 标签 1*17
# print(x_hat); print(y)
omega = np.zeros((17,6))+0.5
b = np.zeros((17,1))+0.3
beta = np.concatenate((omega,b),axis=1)
print(beta); print(beta[:,:6]) #omega

[[0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.3]]
[[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


In [20]:
# 开始计算
def train(beta,x_hat,y,train_cnt):
    oldbeta=beta
    newbeta=beta
    for j in range(train_cnt):
        f1=0       # 一阶导数
        f2=0       # 二阶导数
        oldbeta=newbeta
        for i in range(17):
            # 计算 wx+b
            z=np.dot(oldbeta[i,:].T,x_hat[i,:])
            # print(z)
            # 计算p1和p0
            p1=math.exp(z)/(1+math.exp(z))
            p0=1/(1+math.exp(z))
            f1=f1-x_hat[i,:]*(y[i]-p1)
            f2=f2+np.dot(x_hat[i,:],x_hat[i,:].T)*p1*(1-p1)
            # print(y[i],p1,p0)
        # print(f1,f2)
        # print(pow(f2,-1)*f1)
        newbeta=oldbeta-pow(f2,-1)*f1

    return newbeta

In [21]:
# 得到结果
newbeta=train(beta,x_hat,y,1000)
omega=newbeta[0,:6]
b=newbeta[0,6]

In [6]:
# 计算正确率
flag=0
cnt=0
sum=0
for i in x_hat:
    i=i[:6]
    if np.dot(omega,i)+b < 0:
        flag=0
        if(flag==y[cnt]):
            sum=sum+1
        print("预测是坏瓜")
    else:
        flag=1
        if(flag==y[cnt]):
            sum=sum+1
        print("预测是好瓜")
    cnt=cnt+1
print(sum/17)

预测是好瓜
预测是好瓜
预测是好瓜
预测是好瓜
预测是好瓜
预测是好瓜
预测是坏瓜
预测是好瓜
预测是坏瓜
预测是坏瓜
预测是坏瓜
预测是坏瓜
预测是坏瓜
预测是坏瓜
预测是好瓜
预测是坏瓜
预测是坏瓜
0.8823529411764706


In [7]:
# 单个样例
# print(omega,b)
# 0编号	1色泽	2根蒂	3敲声	4纹理	5脐部	6触感	7密度	8含糖率	 9好瓜
x=input("请输入参数属性").split()
print("输入瓜的特征数据:",x)
x=[seze[x[0]],gendi[x[1]],qiaosheng[x[2]],wenli[x[3]],qibu[x[4]],chugan[x[5]]]
print("数据参数化:",x)
x=np.asarray(x)
if np.dot(omega,x)+b < 0:
    print("预测是坏瓜")
else:
    print("预测是好瓜")

In [52]:
length = len(data)
train_len = int(length*7/10)
train_data=np.concatenate((data[0:train_len//2].astype(np.float),data[8:8+train_len-train_len//2].astype(np.float)))
test_data=np.concatenate((data[train_len//2:8].astype(np.float),data[8+train_len-train_len//2:].astype(np.float)))
print(train_data)
print(test_data)

[[ 1.     1.     1.     1.     1.     1.     1.     0.697  0.46   1.   ]
 [ 2.     0.5    1.     0.5    1.     1.     1.     0.774  0.376  1.   ]
 [ 3.     0.5    1.     1.     1.     1.     1.     0.634  0.264  1.   ]
 [ 4.     1.     1.     0.5    1.     1.     1.     0.608  0.318  1.   ]
 [ 5.     0.     1.     1.     1.     1.     1.     0.556  0.215  1.   ]
 [ 9.     0.5    0.5    0.5    0.5    0.5    1.     0.666  0.091  0.   ]
 [10.     1.     0.     0.     1.     0.     0.     0.243  0.267  0.   ]
 [11.     0.     0.     0.     0.     0.     1.     0.245  0.057  0.   ]
 [12.     0.     1.     1.     0.     0.     0.     0.343  0.099  0.   ]
 [13.     1.     0.5    1.     0.5    1.     1.     0.639  0.161  0.   ]
 [14.     0.     0.5    0.5    0.5    1.     1.     0.657  0.198  0.   ]]
[[ 6.     1.     0.5    1.     1.     0.5    0.     0.403  0.237  1.   ]
 [ 7.     0.5    0.5    1.     0.5    0.5    0.     0.481  0.149  1.   ]
 [ 8.     0.5    0.5    1.     1.     0.5    1.   

In [63]:
import sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data[:,0:7].astype(np.float),data[:,9].astype(np.float),test_size=0.3)
x_train=np.array(x_train)
print(x_train)

[[ 5.   0.   1.   1.   1.   1.   1. ]
 [12.   0.   1.   1.   0.   0.   0. ]
 [ 9.   0.5  0.5  0.5  0.5  0.5  1. ]
 [11.   0.   0.   0.   0.   0.   1. ]
 [13.   1.   0.5  1.   0.5  1.   1. ]
 [15.   0.5  0.5  1.   1.   0.5  0. ]
 [10.   1.   0.   0.   1.   0.   0. ]
 [ 4.   1.   1.   0.5  1.   1.   1. ]
 [ 6.   1.   0.5  1.   1.   0.5  0. ]
 [ 1.   1.   1.   1.   1.   1.   1. ]
 [14.   0.   0.5  0.5  0.5  1.   1. ]]
